title: James Inman
description: technology, mental health, and psychology
baseurl: ''
url: 'https://jamesinman.co.uk'
markdown: kramdown

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Procfile
  - .husky

navigation:
  - title: About
    url: /
    page_id: home
  - title: Coaching
    url: /neurodiversity-coaching-and-technology-mentoring
    page_title: Coaching
  - title: Latest
    url: /latest
    page_title: Latest
  - title: LinkedIn
    url: https://www.linkedin.com/in/jamesfinman/
    page_title: LinkedIn
    icon: linkedin
